# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170524_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_reports_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weekly_reports_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
