# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='priority',
        ),
    ]
