# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170601_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='last_nag_alert',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='nag_after',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
