# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170607_1052'),
        ('api', '0028_remove_check_priority'),
    ]

    operations = [
    ]
