# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170607_1118'),
    ]

    operations = [
    ]
